platform :ios, '13.0'

if File.exist?(File.join(File.dirname(File.realpath(__FILE__)), 'Flutter', 'generated_plugin_registrant.rb'))
  load File.join(File.dirname(File.realpath(__FILE__)), 'Flutter', 'generated_plugin_registrant.rb')
end

target 'Runner' do
  # BƯỚC QUAN TRỌNG: Ép buộc tất cả Pods nạp theo kiểu Static Linkage
  use_frameworks! :linkage => :static
  
  use_modular_headers!

  if respond_to?(:flutter_install_all_ios_pods)
    flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target) if respond_to?(:flutter_additional_ios_build_settings)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      # Sửa lỗi kén Header cho Firebase
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'PERMISSION_CAMERA=1', 'PERMISSION_LOCATION=1']
    end
  end
end